disabled_rules:
  - colon
  - comma
  - opening_brace
  - closing_brace
  - statement_position
  - trailing_newline
  - trailing_whitespace
  - vertical_whitespace
  - void_return
  - trailing_comma

identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - i
    - j
    - k
    - x
    - y
    - z

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 100
  error: 200

file_length:
  warning: 750
  error: 1000
