identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - i
    - j
    - k
    - x
    - y
    - z

trailing_comma:
  mandatory_comma: true

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 100
  error: 200
